# Generated by Django 4.1.4 on 2023-01-01 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_image_no_bg_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='no_bg_img',
        ),
    ]
