# Generated by Django 4.1.4 on 2023-01-02 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_image_author_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='author_id',
            new_name='author',
        ),
    ]
